package main

import (
	"bytes"
	"sort"
	"strings"
)

func renderSchemaReference(workflow schemaDoc, toolDef schemaDoc, tools []toolSchemaDoc) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Schema Reference\n\n")
	buf.WriteString("`deck` validates workflow files against the raw JSON Schema files in `schemas/`. This page is generated from those shipped schemas.\n\n")
	buf.WriteString("## Entry points\n\n")
	buf.WriteString("- `../../schemas/deck-workflow.schema.json`: top-level workflow schema\n")
	buf.WriteString("- `../../schemas/deck-tooldefinition.schema.json`: tool definition schema\n")
	buf.WriteString("- `../../schemas/tools/*.schema.json`: typed step schemas\n\n")
	buf.WriteString("## Workflow schema\n\n")
	if workflow.Description != "" {
		buf.WriteString(workflow.Description + "\n\n")
	}
	buf.WriteString("- required root fields: `" + strings.Join(workflow.Required, "`, `") + "`\n")
	buf.WriteString("- top-level properties: `" + strings.Join(sortedKeys(workflow.Properties), "`, `") + "`\n")
	buf.WriteString("- new prepare workflows should prefer `artifacts.files`, `artifacts.images`, and `artifacts.packages`\n\n")
	buf.WriteString("## Tool definition schema\n\n")
	if toolDef.Description != "" {
		buf.WriteString(toolDef.Description + "\n\n")
	}
	buf.WriteString("- required root fields: `" + strings.Join(toolDef.Required, "`, `") + "`\n")
	buf.WriteString("- top-level properties: `" + strings.Join(sortedKeys(toolDef.Properties), "`, `") + "`\n\n")
	buf.WriteString("## Typed steps\n\n")
	for _, tool := range tools {
		buf.WriteString("### `" + tool.Kind + "`\n\n")
		buf.WriteString("- schema: `../../schemas/tools/" + tool.File + "`\n")
		buf.WriteString("- title: `" + tool.Title + "`\n")
		buf.WriteString("- visibility: `" + tool.Visibility + "`\n")
		if tool.Description != "" {
			buf.WriteString("- description: " + tool.Description + "\n")
		}
		if len(tool.Actions) > 0 {
			buf.WriteString("- actions: `" + strings.Join(tool.Actions, "`, `") + "`\n")
		}
		if len(tool.Required) > 0 {
			buf.WriteString("- required `spec` fields: `" + strings.Join(tool.Required, "`, `") + "`\n")
		}
		if len(tool.SpecFields) > 0 {
			buf.WriteString("- `spec` fields: `" + strings.Join(tool.SpecFields, "`, `") + "`\n")
		}
		buf.WriteString("\n")
	}
	return buf.Bytes()
}

func renderSchemasReadme(tools []toolSchemaDoc) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# deck JSON Schemas\n\n")
	buf.WriteString("This directory contains the raw JSON Schema files shipped with `deck`.\n\n")
	buf.WriteString("## Files\n\n")
	buf.WriteString("- `deck-workflow.schema.json`: top-level workflow schema\n")
	buf.WriteString("- `deck-tooldefinition.schema.json`: tool definition manifest schema\n")
	buf.WriteString("- `tools/*.schema.json`: typed step schemas\n\n")
	buf.WriteString("## Validation model\n\n")
	buf.WriteString("1. Validate the workflow file structure.\n")
	buf.WriteString("2. Validate each step against the schema for its `kind`.\n\n")
	buf.WriteString("For the human-facing reference, read `../docs/reference/schema/index.md`.\n\n")
	buf.WriteString("## Current tool schemas\n\n")
	for _, tool := range tools {
		buf.WriteString("- `tools/" + tool.File + "`: `" + tool.Kind + "` (`" + tool.Visibility + "`)\n")
	}
	return buf.Bytes()
}

func renderToolSchemasReadme(tools []toolSchemaDoc) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Tool Schemas\n\n")
	buf.WriteString("This directory contains JSON Schema files for typed workflow steps.\n\n")
	buf.WriteString("## Current schemas\n\n")
	for _, tool := range tools {
		buf.WriteString("- `" + tool.File + "`: `" + tool.Kind + "` (`" + tool.Visibility + "`)\n")
	}
	buf.WriteString("\nUse `../../docs/reference/schema/index.md` for the generated reference view.\n")
	return buf.Bytes()
}

func nestedProperties(root map[string]any, key string) map[string]any {
	node, ok := root[key].(map[string]any)
	if !ok {
		return nil
	}
	props, _ := node["properties"].(map[string]any)
	return props
}

func nestedRequired(root map[string]any, key string) []string {
	node, ok := root[key].(map[string]any)
	if !ok {
		return nil
	}
	return toStringSlice(node["required"])
}

func nestedEnum(root map[string]any, parent, child string) []string {
	props := nestedProperties(root, parent)
	if props == nil {
		return nil
	}
	field, ok := props[child].(map[string]any)
	if !ok {
		return nil
	}
	values := toStringSlice(field["enum"])
	sort.Strings(values)
	return values
}

func schemaConst(root map[string]any, key string) string {
	field, ok := root[key].(map[string]any)
	if !ok {
		return ""
	}
	value, _ := field["const"].(string)
	return value
}

func sortedKeys(values map[string]any) []string {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func toStringSlice(value any) []string {
	items, ok := value.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if text, ok := item.(string); ok && text != "" {
			out = append(out, text)
		}
	}
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}
