package schemadoc

import "sort"

type FieldDoc struct {
	Description string
	Example     string
}

type ToolMetadata struct {
	Kind           string
	Category       string
	Summary        string
	WhenToUse      string
	MinimalExample string
	CuratedExample string
	ActionNotes    map[string]string
	ActionExamples map[string]string
	FieldDocs      map[string]FieldDoc
	Notes          []string
}

type PageMetadata struct {
	Title            string
	Summary          string
	MinimalExample   string
	RealisticExample string
	FieldDocs        map[string]FieldDoc
	Notes            []string
}

var toolMetadata = map[string]ToolMetadata{
	"Artifacts":    {Kind: "Artifacts", Category: "apply", Summary: "Install or extract pre-collected artifacts on the node.", WhenToUse: "Use this when your apply workflow needs binaries or archives that were prepared into the bundle.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-artifacts\nkind: Artifacts\nspec:\n  artifacts:\n    - source:\n        amd64:\n          bundle:\n            root: files\n            path: bin/linux/amd64/example\n        arm64:\n          bundle:\n            root: files\n            path: bin/linux/arm64/example\n      install:\n        path: /usr/local/bin/example\n", CuratedExample: "kind: Artifacts\nspec:\n  artifacts:\n    - source:\n        amd64:\n          bundle:\n            root: files\n            path: bin/linux/amd64/runc\n        arm64:\n          bundle:\n            root: files\n            path: bin/linux/arm64/runc\n      install:\n        path: /usr/local/sbin/runc\n        mode: \"0755\"\n", FieldDocs: map[string]FieldDoc{"spec.artifacts": {Description: "List of per-architecture artifact entries to install or extract.", Example: "[{source:{...},install:{...}}]"}, "spec.artifacts[].source.amd64": {Description: "Source selection for amd64 nodes. Use a bundle reference, local path, or URL.", Example: "{bundle:{root:files,path:bin/linux/amd64/runc}}"}, "spec.artifacts[].source.arm64": {Description: "Source selection for arm64 nodes. Use a bundle reference, local path, or URL.", Example: "{bundle:{root:files,path:bin/linux/arm64/runc}}"}, "spec.artifacts[].install.path": {Description: "Destination path on the node when installing a single artifact file.", Example: "/usr/local/sbin/runc"}, "spec.artifacts[].extract.destination": {Description: "Directory where an archive artifact should be extracted.", Example: "/opt/cni/bin"}, "spec.fetch.sources[].type": {Description: "Fallback source class used when artifact entries refer to transport sources.", Example: "bundle"}}, Notes: []string{"Each artifact entry must define both `source.amd64` and `source.arm64` so the bundle stays explicit across architectures.", "Each artifact entry must choose exactly one of `install` or `extract`."}},
	"Command":      {Kind: "Command", Category: "advanced", Summary: "Run an explicit command as an escape hatch.", WhenToUse: "Use this only when no typed step expresses the change clearly enough.", CuratedExample: "kind: Command\nspec:\n  command: [\"systemctl\", \"status\", \"containerd\"]\n  timeout: 30s\n"},
	"Containerd":   {Kind: "Containerd", Category: "runtime", Summary: "Write containerd config and registry host settings.", WhenToUse: "Use this when the node runtime needs a default config or registry mirror layout.", CuratedExample: "kind: Containerd\nspec:\n  path: /etc/containerd/config.toml\n  systemdCgroup: true\n  registryHosts:\n    - registry: registry.k8s.io\n      server: https://registry.k8s.io\n      host: http://registry.local:5000\n      capabilities: [pull, resolve]\n      skipVerify: true\n"},
	"Directory":    {Kind: "Directory", Category: "filesystem", Summary: "Ensure a directory exists with an optional mode.", WhenToUse: "Use this before writing files or placing extracted content.", CuratedExample: "kind: Directory\nspec:\n  path: /home/vagrant/.kube\n  mode: \"0755\"\n"},
	"File":         {Kind: "File", Category: "filesystem", Summary: "Manage files through install, copy, edit, or download actions.", WhenToUse: "Use this for most file-oriented host changes instead of generic commands.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-file\nkind: File\nspec:\n  action: download\n  source:\n    url: https://example.invalid/file.tar.gz\n  output:\n    path: files/example.tar.gz\n", CuratedExample: "kind: File\nspec:\n  action: copy\n  src: /etc/kubernetes/admin.conf\n  dest: /home/vagrant/.kube/config\n  owner: vagrant\n  group: vagrant\n  mode: \"0644\"\n", ActionNotes: map[string]string{"download": "Use `download` to pull or bundle a source into a staged output target.", "install": "Use `install` to write inline content or a rendered template to a destination path.", "copy": "Use `copy` to move a file already present on the node.", "edit": "Use `edit` for in-place match/replace style edits."}, ActionExamples: map[string]string{"download": "kind: File\nspec:\n  action: download\n  source:\n    bundle:\n      root: files\n      path: upstream/runc\n  output:\n    path: files/bin/runc\n", "install": "kind: File\nspec:\n  action: install\n  path: /etc/containerd/config.toml\n  contentFromTemplate: containerd-config.toml.tmpl\n  mode: \"0644\"\n", "copy": "kind: File\nspec:\n  action: copy\n  src: /etc/kubernetes/admin.conf\n  dest: /home/vagrant/.kube/config\n  owner: vagrant\n  group: vagrant\n  mode: \"0644\"\n", "edit": "kind: File\nspec:\n  action: edit\n  path: /etc/containerd/config.toml\n  edits:\n    - match: SystemdCgroup = false\n      with: SystemdCgroup = true\n"}, FieldDocs: map[string]FieldDoc{"spec.action": {Description: "Selects the file operation mode and therefore changes which sibling fields become required.", Example: "copy"}, "spec.path": {Description: "Target path for `install` or `edit` actions.", Example: "/etc/containerd/config.toml"}, "spec.src": {Description: "Source path already present on the node for `copy`.", Example: "/etc/kubernetes/admin.conf"}, "spec.dest": {Description: "Destination path on the node for `copy`.", Example: "/home/vagrant/.kube/config"}, "spec.source": {Description: "Structured download source used by `download`.", Example: "{url:https://example.invalid/file.tar.gz}"}, "spec.source.bundle": {Description: "Bundle-root reference for offline file staging.", Example: "{root:files,path:bin/linux/amd64/runc}"}, "spec.output.path": {Description: "Bundle-relative output path for the downloaded file.", Example: "files/bin/runc"}, "spec.edits": {Description: "Ordered match/replace edit rules for `edit`.", Example: "[{match:SystemdCgroup = false,with:SystemdCgroup = true}]"}}, Notes: []string{"`File` is usually the best first choice for host file changes because it stays declarative and validates action-specific inputs.", "`download` writes into a bundle-style output target, while `copy`, `install`, and `edit` operate on live node paths."}},
	"Image":        {Kind: "Image", Category: "prepare", Summary: "Download or verify container images.", WhenToUse: "Use this when workflows need image presence checks or bundle-time image collection.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-image\nkind: Image\nspec:\n  action: present\n  images:\n    - registry.k8s.io/pause:3.9\n", CuratedExample: "kind: Image\nspec:\n  action: present\n  images:\n    - registry.k8s.io/kube-apiserver:v1.30.1\n    - registry.k8s.io/kube-controller-manager:v1.30.1\n", ActionNotes: map[string]string{"download": "Use `download` during prepare to collect images into bundle outputs.", "present": "Use `present` to assert that required images already exist locally."}, ActionExamples: map[string]string{"download": "kind: Image\nspec:\n  action: download\n  images:\n    - registry.k8s.io/kube-apiserver:v1.30.1\n  output:\n    path: images/control-plane.tar\n", "present": "kind: Image\nspec:\n  action: present\n  command: [ctr, -n, k8s.io, images, list, -q]\n  images:\n    - registry.k8s.io/kube-apiserver:v1.30.1\n"}, FieldDocs: map[string]FieldDoc{"spec.action": {Description: "Chooses whether the step gathers images or verifies local image presence.", Example: "present"}, "spec.images": {Description: "Fully qualified image references to download or verify.", Example: "[registry.k8s.io/pause:3.9]"}, "spec.command": {Description: "Optional image-listing command used by `present` when the default runtime command is not appropriate.", Example: "[ctr,-n,k8s.io,images,list,-q]"}, "spec.output": {Description: "Bundle output settings used when downloaded image artifacts are written.", Example: "{layout:oci-archive,path:images/control-plane.tar}"}, "spec.backend": {Description: "Backend-specific settings such as runtime or transport configuration.", Example: "{runtime:containerd}"}}, Notes: []string{"Prefer `Image` over ad-hoc shell commands so workflows keep an explicit list of required images.", "Use explicit image tags or digests to keep prepared bundles reproducible."}},
	"Inspection":   {Kind: "Inspection", Category: "prepare", Summary: "Run host inspection checks before prepare execution.", WhenToUse: "Use this at the start of prepare workflows to fail early on unsupported hosts.", CuratedExample: "kind: Inspection\nspec:\n  checks: [os, arch, swap]\n  failFast: true\n"},
	"KernelModule": {Kind: "KernelModule", Category: "system", Summary: "Load and persist kernel modules.", WhenToUse: "Use this for modules that must be present before networking or container runtime setup.", CuratedExample: "kind: KernelModule\nspec:\n  name: br_netfilter\n  load: true\n  persist: true\n  persistFile: /etc/modules-load.d/k8s.conf\n"},
	"Kubeadm":      {Kind: "Kubeadm", Category: "kubernetes", Summary: "Run kubeadm init, join, or reset actions.", WhenToUse: "Use this for bootstrap lifecycle steps after host prerequisites are ready.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-kubeadm\nkind: Kubeadm\nspec:\n  action: init\n  outputJoinFile: /tmp/deck/join.txt\n", CuratedExample: "kind: Kubeadm\nspec:\n  action: init\n  mode: real\n  outputJoinFile: /tmp/deck/join.txt\n  podNetworkCIDR: 10.244.0.0/16\n  criSocket: unix:///run/containerd/containerd.sock\n  ignorePreflightErrors: [Swap]\n", ActionNotes: map[string]string{"init": "`init` bootstraps a new control plane and writes a join artifact.", "join": "`join` consumes a prepared join file and joins the node to a cluster.", "reset": "`reset` tears down kubeadm-managed state before rebuilding or reprovisioning."}, ActionExamples: map[string]string{"init": "kind: Kubeadm\nspec:\n  action: init\n  mode: real\n  outputJoinFile: /tmp/deck/join.txt\n  podNetworkCIDR: 10.244.0.0/16\n", "join": "kind: Kubeadm\nspec:\n  action: join\n  joinFile: /tmp/deck/join.txt\n  criSocket: unix:///run/containerd/containerd.sock\n", "reset": "kind: Kubeadm\nspec:\n  action: reset\n  force: true\n  removePaths: [/etc/cni/net.d, /var/lib/etcd]\n"}, FieldDocs: map[string]FieldDoc{"spec.action": {Description: "Chooses which kubeadm subcommand contract applies.", Example: "init"}, "spec.mode": {Description: "Controls whether the step performs a real kubeadm invocation or a stubbed contract-oriented run.", Example: "real"}, "spec.outputJoinFile": {Description: "Path where the generated join command or token data will be written after `init`.", Example: "/tmp/deck/join.txt"}, "spec.joinFile": {Description: "Path to a prepared join artifact used by `join`.", Example: "/tmp/deck/join.txt"}, "spec.ignorePreflightErrors": {Description: "Explicit kubeadm preflight checks to ignore when bootstrapping constrained hosts.", Example: "[Swap]"}, "spec.removePaths": {Description: "Paths removed during `reset` cleanup.", Example: "[/etc/cni/net.d,/var/lib/etcd]"}}, Notes: []string{"The action controls the contract: `init` requires `outputJoinFile`, `join` requires `joinFile`, and `reset` focuses on cleanup behavior.", "Keep host preparation steps like `Containerd`, `Swap`, `KernelModule`, and `Sysctl` ahead of `Kubeadm` for clearer bootstrap failures."}},
	"PackageCache": {Kind: "PackageCache", Category: "packages", Summary: "Refresh package metadata with repo filtering.", WhenToUse: "Use this after writing repo definitions and before package install steps that depend on fresh metadata.", CuratedExample: "kind: PackageCache\nspec:\n  manager: apt\n  clean: true\n  update: true\n  restrictToRepos:\n    - /etc/apt/sources.list.d/offline.list\n"},
	"Packages":     {Kind: "Packages", Category: "packages", Summary: "Download or install package sets.", WhenToUse: "Use this for package-manager driven dependencies instead of shelling out directly.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-packages\nkind: Packages\nspec:\n  action: install\n  packages: [kubelet]\n", CuratedExample: "kind: Packages\nspec:\n  action: install\n  packages: [kubelet, kubeadm, kubectl]\n", ActionNotes: map[string]string{"download": "`download` gathers packages into a prepare artifact set.", "install": "`install` applies packages on the node using the available package manager."}, ActionExamples: map[string]string{"download": "kind: Packages\nspec:\n  action: download\n  packages: [kubelet, kubeadm, kubectl]\n  repo:\n    mirror: http://repo.local/kubernetes\n", "install": "kind: Packages\nspec:\n  action: install\n  packages: [kubelet, kubeadm, kubectl]\n  source:\n    type: local-repo\n    path: /opt/deck/repos/kubernetes\n"}, FieldDocs: map[string]FieldDoc{"spec.action": {Description: "Chooses whether the package list is collected during prepare or installed on the node.", Example: "install"}, "spec.packages": {Description: "Package names to gather or install.", Example: "[kubelet,kubeadm,kubectl]"}, "spec.source": {Description: "Optional local repository source used when installs should come from a prepared repo path.", Example: "{type:local-repo,path:/opt/deck/repos/kubernetes}"}, "spec.restrictToRepos": {Description: "Limit package manager visibility to the listed repositories during the operation.", Example: "[offline-kubernetes]"}, "spec.excludeRepos": {Description: "Exclude the listed repositories while resolving packages.", Example: "[updates]"}}, Notes: []string{"Use `Packages` with `Repository` and `PackageCache` for a complete typed package-management flow.", "Keeping the same package list across `download` and `install` helps maintain offline parity."}},
	"Repository":   {Kind: "Repository", Category: "packages", Summary: "Configure apt or yum repository definitions.", WhenToUse: "Use this before refreshing caches or installing packages from a local mirror.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-repository\nkind: Repository\nspec:\n  action: configure\n  format: apt\n  repositories:\n    - id: offline\n      baseurl: http://repo.local/debian\n", CuratedExample: "kind: Repository\nspec:\n  action: configure\n  format: apt\n  replaceExisting: true\n  refreshCache:\n    clean: true\n    update: true\n  repositories:\n    - id: offline\n      baseurl: http://repo.local/debian\n      trusted: true\n", ActionNotes: map[string]string{"configure": "`configure` writes or rewrites repository definitions and optional refresh behavior."}, ActionExamples: map[string]string{"configure": "kind: Repository\nspec:\n  action: configure\n  format: apt\n  path: /etc/apt/sources.list.d/offline.list\n  repositories:\n    - id: offline\n      baseurl: http://repo.local/debian\n      trusted: true\n"}, FieldDocs: map[string]FieldDoc{"spec.format": {Description: "Repository file style to emit for the target host family.", Example: "apt"}, "spec.path": {Description: "Optional explicit output path for the generated repository file.", Example: "/etc/apt/sources.list.d/offline.list"}, "spec.replaceExisting": {Description: "Replace existing repo definitions at the target path before writing the new one.", Example: "true"}, "spec.refreshCache": {Description: "Optional package metadata refresh that can run after repository files are written.", Example: "{clean:true,update:true}"}, "spec.repositories": {Description: "Repository entries passed through to the package-manager-specific writer.", Example: "[{id:offline,baseurl:http://repo.local/debian}]"}}, Notes: []string{"`Repository` only defines repository files; combine it with `PackageCache` when the package manager needs a metadata refresh.", "Keep repository definitions explicit and mirror-specific instead of mutating the host's default online sources."}},
	"Service":      {Kind: "Service", Category: "system", Summary: "Start, stop, enable, or reload local services.", WhenToUse: "Use this after config changes that need a service lifecycle action.", CuratedExample: "kind: Service\nspec:\n  name: containerd\n  enabled: true\n  state: started\n"},
	"Swap":         {Kind: "Swap", Category: "system", Summary: "Enable or disable swap and its persistence.", WhenToUse: "Use this for Kubernetes-oriented host prep where swap policy matters.", CuratedExample: "kind: Swap\nspec:\n  disable: true\n  persist: true\n"},
	"Symlink":      {Kind: "Symlink", Category: "filesystem", Summary: "Create or replace a symbolic link.", WhenToUse: "Use this when tools or runtimes expect a stable path alias.", CuratedExample: "kind: Symlink\nspec:\n  path: /usr/bin/runc\n  target: /usr/local/sbin/runc\n  force: true\n"},
	"Sysctl":       {Kind: "Sysctl", Category: "system", Summary: "Write and optionally apply sysctl values.", WhenToUse: "Use this for kernel tunables that must survive reboot and may need immediate application.", CuratedExample: "kind: Sysctl\nspec:\n  writeFile: /etc/sysctl.d/99-kubernetes-cri.conf\n  apply: true\n  values:\n    net.ipv4.ip_forward: 1\n"},
	"SystemdUnit":  {Kind: "SystemdUnit", Category: "system", Summary: "Write a systemd unit file and optionally manage the service.", WhenToUse: "Use this when workflows need to install or override a custom unit definition.", CuratedExample: "kind: SystemdUnit\nspec:\n  path: /etc/systemd/system/kubelet.service\n  contentFromTemplate: kubelet.service.tmpl\n  daemonReload: true\n  service:\n    name: kubelet\n    enabled: true\n    state: started\n"},
	"Wait":         {Kind: "Wait", Category: "control-flow", Summary: "Wait for command, service, file, or port conditions.", WhenToUse: "Use this between dependent steps when the host needs time to converge.", MinimalExample: "apiVersion: deck/v1alpha1\nid: example-wait\nkind: Wait\nspec:\n  action: serviceActive\n  name: containerd\n", CuratedExample: "kind: Wait\nspec:\n  action: fileExists\n  path: /etc/kubernetes/admin.conf\n  type: file\n  nonEmpty: true\n  interval: 2s\n  timeout: 5m\n", ActionNotes: map[string]string{"serviceActive": "Wait until a service is active.", "commandSuccess": "Poll a command until it exits successfully.", "fileExists": "Wait for a file or directory path to appear.", "fileAbsent": "Wait for a file or directory path to disappear.", "tcpPortOpen": "Wait for a TCP listener to accept connections.", "tcpPortClosed": "Wait for a TCP port to stop accepting connections."}, ActionExamples: map[string]string{"serviceActive": "kind: Wait\nspec:\n  action: serviceActive\n  name: containerd\n  interval: 2s\n  timeout: 2m\n", "commandSuccess": "kind: Wait\nspec:\n  action: commandSuccess\n  command: [test, -f, /etc/kubernetes/admin.conf]\n  interval: 2s\n  timeout: 2m\n", "fileExists": "kind: Wait\nspec:\n  action: fileExists\n  path: /etc/kubernetes/admin.conf\n  type: file\n  nonEmpty: true\n  interval: 2s\n  timeout: 5m\n", "fileAbsent": "kind: Wait\nspec:\n  action: fileAbsent\n  path: /var/lib/etcd/member\n  interval: 2s\n  timeout: 2m\n", "tcpPortOpen": "kind: Wait\nspec:\n  action: tcpPortOpen\n  port: \"6443\"\n  interval: 2s\n  timeout: 5m\n", "tcpPortClosed": "kind: Wait\nspec:\n  action: tcpPortClosed\n  port: \"10250\"\n  interval: 2s\n  timeout: 2m\n"}, FieldDocs: map[string]FieldDoc{"spec.action": {Description: "Chooses which condition is polled by the wait loop.", Example: "fileExists"}, "spec.name": {Description: "Service name required by `serviceActive`.", Example: "containerd"}, "spec.command": {Description: "Command vector required by `commandSuccess`.", Example: "[test,-f,/etc/kubernetes/admin.conf]"}, "spec.path": {Description: "Filesystem path checked by `fileExists` or `fileAbsent`.", Example: "/etc/kubernetes/admin.conf"}, "spec.port": {Description: "TCP port checked by `tcpPortOpen` or `tcpPortClosed`.", Example: "6443"}, "spec.interval": {Description: "Polling interval between retries.", Example: "2s"}, "spec.timeout": {Description: "Overall time budget for the wait condition before failure.", Example: "5m"}}, Notes: []string{"`Wait` should bridge convergence gaps between typed steps, not replace the main configuration action itself.", "Keep waits specific so failures explain exactly which dependency did not become ready."}},
}

func ToolMeta(kind string) ToolMetadata {
	meta, ok := toolMetadata[kind]
	if !ok {
		return ToolMetadata{Kind: kind, Category: "other", Summary: "Generated schema reference.", WhenToUse: "Use this schema according to the workflow contract."}
	}
	return meta
}

func ToolKinds() []string {
	kinds := make([]string, 0, len(toolMetadata))
	for kind := range toolMetadata {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)
	return kinds
}

func WorkflowMeta() PageMetadata {
	return PageMetadata{
		Title:            "Workflow Schema",
		Summary:          "Top-level workflow authoring reference for deck workflows.",
		MinimalExample:   "role: apply\nversion: v1alpha1\nsteps:\n  - id: install-config\n    apiVersion: deck/v1alpha1\n    kind: File\n    spec:\n      action: install\n      path: /etc/example.conf\n      content: hello\n",
		RealisticExample: "role: prepare\nversion: v1alpha1\nartifacts:\n  files:\n    - group: runtime-binaries\n      items:\n        - id: runc\n          source:\n            url: https://mirror.example.invalid/runc\n          output:\n            path: bin/runc\n",
		FieldDocs: map[string]FieldDoc{
			"role":             {Description: "Workflow role. `prepare` builds offline artifacts and `apply` changes the local node.", Example: "apply"},
			"artifacts":        {Description: "Declarative prepare inventory that replaces legacy prepare download steps.", Example: "{files:[...],images:[...],packages:[...]}"},
			"imports":          {Description: "Scenario or component imports resolved relative to the workflow/component model.", Example: "[common/base.yaml]"},
			"phases":           {Description: "Ordered execution phases. Each phase can contain imports, steps, or both.", Example: "[{name:install,steps:[...]}]"},
			"steps":            {Description: "Flat step list for workflows that do not need named phases.", Example: "[{id:configure-runtime,kind:Containerd,spec:{...}}]"},
			"steps[].kind":     {Description: "Typed step kind selected from the shipped public step inventory.", Example: "File"},
			"steps[].spec":     {Description: "Action-specific step payload validated against the schema for the chosen kind.", Example: "{action:install,path:/etc/example.conf,content:hello}"},
			"phases[].name":    {Description: "Stable phase name used for ordering and selective execution.", Example: "install"},
			"phases[].imports": {Description: "Imports that expand into this phase before step execution.", Example: "[{path:k8s/containerd-kubelet.yaml}]"},
		},
		Notes: []string{"A workflow must define at least one of `artifacts`, `imports`, `phases`, or `steps`.", "A workflow cannot define both top-level `phases` and top-level `steps` at the same time.", "Each step still validates against its own kind-specific schema after the top-level workflow schema passes."},
	}
}

func ToolDefinitionMeta() PageMetadata {
	return PageMetadata{
		Title:            "Tool Definition Schema",
		Summary:          "Reference for tool definition manifests used to describe typed workflow tools.",
		MinimalExample:   "apiVersion: deck/v1\nkind: ToolDefinition\nmetadata:\n  name: File\nspec:\n  version: v1\n  summary: Manage files\n  category: shared\n  inputSchema: {}\n",
		RealisticExample: "apiVersion: deck/v1\nkind: ToolDefinition\nmetadata:\n  name: File\n  description: Manage files on the local node\nspec:\n  version: v1\n  summary: Manage files on the local node\n  category: shared\n  offlineAllowed: true\n  requires:\n    root: true\n  inputSchema: {}\n  idempotency:\n    mode: by-output\n    keys: [path]\n",
		FieldDocs: map[string]FieldDoc{
			"metadata.name":                  {Description: "Public tool kind name described by this manifest.", Example: "File"},
			"spec.version":                   {Description: "Manifest version for the tool definition contract.", Example: "v1"},
			"spec.summary":                   {Description: "Short product-facing summary of the tool's purpose.", Example: "Manage files on the local node."},
			"spec.category":                  {Description: "High-level grouping used for docs and discovery.", Example: "shared"},
			"spec.inputSchema":               {Description: "Schema fragment describing the tool's input contract.", Example: "{}"},
			"spec.outputContract":            {Description: "Declared outputs or state keys produced by the tool.", Example: "{artifacts:[joinFile],stateKeys:[nodeReady]}"},
			"spec.idempotency.mode":          {Description: "How callers should reason about repeated runs of the tool.", Example: "by-output"},
			"spec.requires.containerRuntime": {Description: "Whether the tool expects a container runtime on the node.", Example: "required"},
		},
		Notes: []string{"`ToolDefinition` describes a typed tool contract rather than a workflow step instance.", "`inputSchema` stays open-ended because it embeds another schema fragment rather than a fixed workflow payload."},
	}
}
