package schemadoc

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type PageInput struct {
	Family      string
	PageSlug    string
	Title       string
	Summary     string
	Description string
	Variants    []VariantInput
}

type VariantInput struct {
	Kind        string
	Title       string
	Description string
	SchemaPath  string
	Schema      map[string]any
	Meta        ToolMetadata
	Required    []string
	Spec        map[string]any
	Outputs     []string
	DocsOrder   int
}

type Field struct {
	Path        string
	Type        string
	Required    bool
	Default     string
	Enum        string
	Description string
	Example     string
}

type PageOverrides struct {
	FieldDocs map[string]FieldDoc
	Example   string
	Notes     []string
}

func RenderToolPage(in PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	title := firstNonEmpty(in.Title, familyTitleFallback(in.Family))
	summary := firstNonEmpty(in.Summary, in.Description, "Reference for typed workflow steps in this family.")
	buf.WriteString("# " + title + "\n\n")
	buf.WriteString(summary + "\n\n")
	buf.WriteString("## Summary\n\n")
	buf.WriteString("- family: `" + in.Family + "`\n")
	if len(in.Variants) > 0 {
		buf.WriteString("- kinds: `" + strings.Join(pageKinds(in.Variants), "`, `") + "`\n")
	}
	buf.WriteString("\n## Shared Step Fields\n\n")
	buf.WriteString("Shared step envelope fields such as `id`, `apiVersion`, `kind`, `when`, `retry`, `timeout`, `register`, and `metadata` are documented in [Workflow Schema](../workflow.md).\n")
	if len(in.Variants) > 1 {
		buf.WriteString("\n## Supported Kinds\n\n")
		for _, variant := range sortedVariants(in.Variants) {
			buf.WriteString("- `" + variant.Kind + "`: " + firstNonEmpty(variant.Meta.Summary, variant.Description) + "\n")
		}
	}
	for _, variant := range sortedVariants(in.Variants) {
		fields := CollectFields(variant.Schema)
		applyFieldDocs(fields, variant.Meta.FieldDocs)
		rules := ExtractRules(variant.Spec, "spec")
		buf.WriteString("\n## `" + variant.Kind + "`\n\n")
		buf.WriteString(firstNonEmpty(variant.Meta.Summary, variant.Description) + "\n\n")
		buf.WriteString("- schema: `../../../" + variant.SchemaPath + "`\n")
		if len(variant.Outputs) > 0 {
			buf.WriteString("- outputs: `" + strings.Join(variant.Outputs, "`, `") + "`\n")
		}
		if strings.TrimSpace(variant.Meta.WhenToUse) != "" {
			buf.WriteString("\n### When To Use\n\n" + variant.Meta.WhenToUse + "\n")
		}
		buf.WriteString("\n### Example\n\n```yaml\n")
		example, err := toolExample(variant)
		if err != nil {
			buf.WriteString("# error: unable to render example\n")
			buf.WriteString("```\n")
			return buf.Bytes()
		}
		buf.WriteString(example)
		buf.WriteString("```\n")
		buf.WriteString("\n### Spec Fields\n\n")
		buf.WriteString(renderFieldTable(directChildFields(fields, "spec")))
		if nested := renderNestedSections(fields, "spec"); nested != "" {
			buf.WriteString("\n### Nested Objects\n\n")
			buf.WriteString(nested)
		}
		if len(rules) > 0 {
			buf.WriteString("\n### Validation Rules\n\n")
			for _, rule := range rules {
				buf.WriteString("- " + rule + "\n")
			}
		}
		if len(variant.Meta.Notes) > 0 {
			buf.WriteString("\n### Notes\n\n")
			for _, note := range variant.Meta.Notes {
				buf.WriteString("- " + note + "\n")
			}
		}
	}
	buf.WriteString("\n## Related\n\n")
	buf.WriteString("- [Schema Reference](../README.md)\n")
	return buf.Bytes()
}

func RenderToolsIndex(inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Tool Schemas\n\n")
	buf.WriteString("Reference documentation for each typed workflow step supported by deck.\n\n")
	for _, in := range inputs {
		buf.WriteString("## [" + in.Title + "](" + in.PageSlug + ".md)\n\n")
		buf.WriteString("- **Summary**: " + firstNonEmpty(in.Summary, in.Description) + "\n")
		buf.WriteString("- **Kinds**: `" + strings.Join(pageKinds(in.Variants), "`, `") + "`\n")
		buf.WriteString("\n")
	}
	return buf.Bytes()
}

func RenderSchemaIndex(workflowPath, toolDefPath string, inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Schema Reference\n\n")
	buf.WriteString("This is the entrypoint for deck's generated schema documentation.\n\n")
	buf.WriteString("## Core Schemas\n\n")
	buf.WriteString("- [Workflow Schema](workflow.md)\n")
	buf.WriteString("- [Component Fragment Schema](component-fragment.md)\n")
	buf.WriteString("- [Tool Definition Schema](tool-definition.md)\n")
	buf.WriteString("- [Available Tool Steps](tools/README.md)\n\n")
	buf.WriteString("## Raw JSON Schemas\n\n")
	buf.WriteString("- `../../../" + workflowPath + "`\n")
	buf.WriteString("- `../../../" + toolDefPath + "`\n")
	buf.WriteString("- `../../../schemas/tools/*.schema.json`\n\n")
	buf.WriteString("## Tool Step Quick Links\n\n")
	for _, in := range inputs {
		buf.WriteString("- [" + in.Title + "](tools/" + in.PageSlug + ".md)\n")
	}
	return buf.Bytes()
}

func RenderWorkflowPage(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + firstNonEmpty(meta.Title, "Workflow Schema") + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Top-level workflow authoring reference for deck workflows.") + "\n\n")
	buf.WriteString("- schema: `../../../" + schemaPath + "`\n\n")
	buf.WriteString("## Example\n\n```yaml\n" + firstNonEmpty(meta.Example, "version: v1alpha1\nsteps:\n  - id: example-step\n    kind: WriteFile\n    spec:\n      path: /tmp/example\n      content: hello\n") + "```\n")
	fields := CollectFields(schema)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("\n## Fields\n\n")
	buf.WriteString(renderFieldTable(directChildFields(fields, "")))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	buf.WriteString("\n## Validation Rules\n\n")
	for _, rule := range ExtractRules(schema, "") {
		buf.WriteString("- " + rule + "\n")
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func RenderToolDefinitionPage(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + firstNonEmpty(meta.Title, "Tool Definition Schema") + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Reference for tool definition manifests.") + "\n\n")
	buf.WriteString("- schema: `../../../" + schemaPath + "`\n\n")
	buf.WriteString("## Example\n\n```yaml\n" + firstNonEmpty(meta.Example, "apiVersion: deck/v1\nkind: ToolDefinition\nmetadata:\n  name: Example\nspec:\n  version: v1\n  summary: Example tool\n  category: shared\n  inputSchema: {}\n") + "```\n")
	fields := CollectFields(schema)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("## Fields\n\n")
	buf.WriteString(renderFieldTable(directChildFields(fields, "")))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	buf.WriteString("\n## Validation Rules\n\n")
	for _, rule := range ExtractRules(schema, "") {
		buf.WriteString("- " + rule + "\n")
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func RenderComponentFragmentPage(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + firstNonEmpty(meta.Title, "Component Fragment Schema") + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Reference for reusable workflow component fragments.") + "\n\n")
	buf.WriteString("- schema: `../../../" + schemaPath + "`\n\n")
	buf.WriteString("## Example\n\n```yaml\n" + firstNonEmpty(meta.Example, "steps:\n  - id: example-step\n    kind: Command\n    spec:\n      command: [echo, hello]\n") + "```\n")
	fields := CollectFields(schema)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("\n## Fields\n\n")
	buf.WriteString(renderFieldTable(directChildFields(fields, "")))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func CollectFields(schema map[string]any) []Field {
	var fields []Field
	collectFields(schema, schema, "", &fields)
	return dedupeFields(fields)
}

func collectFields(root, node map[string]any, prefix string, fields *[]Field) {
	node = resolveSchemaNode(root, node)
	props, _ := node["properties"].(map[string]any)
	if len(props) == 0 {
		return
	}
	req := requiredSet(node["required"])
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		child = resolveSchemaNode(root, child)
		path := joinPath(prefix, key)
		field := Field{
			Path:        path,
			Type:        fieldType(root, child),
			Required:    req[key],
			Default:     valueString(child["default"]),
			Enum:        enumString(child["enum"]),
			Description: stringValue(child["description"]),
			Example:     inferExample(root, child),
		}
		*fields = append(*fields, field)
		if field.Type == "object" {
			collectFields(root, child, path, fields)
		}
		items, _ := resolveSchemaNode(root, child)["items"].(map[string]any)
		items = resolveSchemaNode(root, items)
		if field.Type == "array<object>" && len(items) > 0 {
			collectFields(root, items, path+"[]", fields)
		}
	}
}

func ExtractRules(node map[string]any, prefix string) []string {
	var rules []string
	if anyOf, ok := node["anyOf"].([]any); ok {
		var requiredGroups []string
		for _, raw := range anyOf {
			entry, _ := raw.(map[string]any)
			req := toStrings(entry["required"])
			if len(req) > 0 {
				requiredGroups = append(requiredGroups, strings.Join(req, ", "))
			}
		}
		if len(requiredGroups) > 0 && prefix == "" {
			groups := make([]string, 0, len(requiredGroups))
			for _, group := range requiredGroups {
				groups = append(groups, "`"+group+"`")
			}
			rules = append(rules, "At least one of the top-level groups "+joinWithFinalConjunction(groups, "or")+" must be present.")
		}
		for _, raw := range anyOf {
			entry, _ := raw.(map[string]any)
			if strings.Contains(fmt.Sprint(entry), "const") {
				rules = append(rules, "At least one of the listed branches must match.")
				break
			}
		}
	}
	if oneOf, ok := node["oneOf"].([]any); ok && len(oneOf) > 0 {
		for _, raw := range oneOf {
			entry, _ := raw.(map[string]any)
			req := toStrings(entry["required"])
			notReq := toStrings(mapValue(entry, "not", "required"))
			if len(req) == 1 && len(notReq) == 1 {
				rules = append(rules, fmt.Sprintf("Exactly one of %s or %s must be set.", prefixPath(prefix, req[0]), prefixPath(prefix, notReq[0])))
				break
			}
		}
	}
	if allOf, ok := node["allOf"].([]any); ok {
		for _, raw := range allOf {
			entry, _ := raw.(map[string]any)
			ifNode, _ := entry["if"].(map[string]any)
			thenNode, _ := entry["then"].(map[string]any)
			action := stringValue(mapValue(ifNode, "properties", "action", "const"))
			if action == "" {
				enumAction := toStrings(mapValue(ifNode, "properties", "action", "enum"))
				if len(enumAction) > 0 {
					required := toStrings(thenNode["required"])
					if len(required) > 0 {
						rules = append(rules, fmt.Sprintf("When `%s.action` is one of `%s`, %s are required.", prefix, strings.Join(enumAction, "`, `"), prefixDotJoin(prefix, required)))
					}
				}
				continue
			}
			required := toStrings(thenNode["required"])
			if len(required) > 0 {
				rules = append(rules, fmt.Sprintf("When `%s.action=%s`, %s are required.", prefix, action, prefixDotJoin(prefix, required)))
			}
			if anyOf, ok := thenNode["anyOf"].([]any); ok && len(anyOf) > 0 {
				var choices []string
				for _, choiceRaw := range anyOf {
					choice, _ := choiceRaw.(map[string]any)
					choiceReq := toStrings(choice["required"])
					for _, item := range choiceReq {
						choices = append(choices, fmt.Sprintf("`%s.%s`", prefix, item))
					}
				}
				if len(choices) > 0 {
					rules = append(rules, fmt.Sprintf("When `%s.action=%s`, at least one of %s must be set.", prefix, action, strings.Join(choices, " or ")))
				}
			}
		}
	}
	if notNode, ok := node["not"].(map[string]any); ok {
		if allOf, ok := notNode["allOf"].([]any); ok && len(allOf) > 0 && prefix == "" {
			rules = append(rules, "Top-level `phases` and top-level `steps` cannot both be set in the same workflow.")
		}
	}
	return dedupeStrings(rules)
}

func joinWithFinalConjunction(values []string, conjunction string) string {
	if len(values) == 0 {
		return ""
	}
	if len(values) == 1 {
		return values[0]
	}
	if len(values) == 2 {
		return values[0] + " " + conjunction + " " + values[1]
	}
	return strings.Join(values[:len(values)-1], ", ") + ", " + conjunction + " " + values[len(values)-1]
}

func pageKinds(variants []VariantInput) []string {
	kinds := make([]string, 0, len(variants))
	for _, variant := range sortedVariants(variants) {
		kinds = append(kinds, variant.Kind)
	}
	return kinds
}

func sortedVariants(variants []VariantInput) []VariantInput {
	out := append([]VariantInput(nil), variants...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].DocsOrder != out[j].DocsOrder {
			return out[i].DocsOrder < out[j].DocsOrder
		}
		return out[i].Kind < out[j].Kind
	})
	return out
}

func toolExample(in VariantInput) (string, error) {
	if strings.TrimSpace(in.Meta.Example) != "" {
		return in.Meta.Example, nil
	}
	obj := map[string]any{
		"id":         "example-" + strings.ToLower(in.Kind),
		"apiVersion": "deck/v1alpha1",
		"kind":       in.Kind,
		"spec":       minimalObject(in.Spec),
	}
	raw, err := yaml.Marshal(obj)
	if err != nil {
		return "", fmt.Errorf("marshal minimal tool example: %w", err)
	}
	return string(raw), nil
}

func applyFieldDocs(fields []Field, overrides map[string]FieldDoc) {
	for i := range fields {
		override, ok := overrides[fields[i].Path]
		if !ok {
			continue
		}
		if strings.TrimSpace(override.Description) != "" {
			fields[i].Description = override.Description
		}
		if strings.TrimSpace(override.Example) != "" {
			fields[i].Example = override.Example
		}
	}
}

func minimalObject(node map[string]any) map[string]any {
	obj := map[string]any{}
	req := requiredSet(node["required"])
	props, _ := node["properties"].(map[string]any)
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child, _ := props[key].(map[string]any)
		if !req[key] && key != "action" {
			continue
		}
		obj[key] = minimalValue(node, child)
	}
	if allOf, ok := node["allOf"].([]any); ok {
		for _, raw := range allOf {
			entry, _ := raw.(map[string]any)
			action := stringValue(mapValue(entry, "if", "properties", "action", "const"))
			if action != "" {
				obj["action"] = action
				for _, field := range toStrings(mapValue(entry, "then", "required")) {
					if child, ok := props[field].(map[string]any); ok {
						obj[field] = minimalValue(node, child)
					}
				}
				for _, anyRaw := range toAnySliceFromUnknown(mapValue(entry, "then", "anyOf")) {
					choice, _ := anyRaw.(map[string]any)
					for _, field := range toStrings(choice["required"]) {
						if child, ok := props[field].(map[string]any); ok {
							obj[field] = minimalValue(node, child)
							break
						}
					}
					break
				}
				break
			}
		}
	}
	applyBranchRequirements(obj, node, props)
	return obj
}

func applyBranchRequirements(obj map[string]any, node map[string]any, props map[string]any) {
	for _, groupKey := range []string{"anyOf", "oneOf"} {
		for _, raw := range toAnySliceFromUnknown(node[groupKey]) {
			branch, _ := raw.(map[string]any)
			for _, field := range toStrings(branch["required"]) {
				if _, exists := obj[field]; exists {
					continue
				}
				if child, ok := props[field].(map[string]any); ok {
					obj[field] = minimalValue(node, child)
					return
				}
			}
		}
	}
}

func minimalValue(root, node map[string]any) any {
	node = resolveSchemaNode(root, node)
	if value := node["const"]; value != nil {
		return value
	}
	if values := toStrings(node["enum"]); len(values) > 0 {
		return values[0]
	}
	switch fieldType(root, node) {
	case "string":
		return "example"
	case "integer":
		return 1
	case "number":
		return 1
	case "boolean":
		return true
	case "array<string>":
		return []string{"example"}
	case "array<object>":
		items, _ := node["items"].(map[string]any)
		return []any{minimalObject(resolveSchemaNode(root, items))}
	case "array":
		return []any{"example"}
	case "object":
		return minimalObject(node)
	default:
		return "example"
	}
}

func renderFieldTable(fields []Field) string {
	if len(fields) == 0 {
		return "No documented fields.\n"
	}
	var buf bytes.Buffer
	buf.WriteString("| Key | Type | Required | Default | Enum | Description | Example |\n")
	buf.WriteString("|---|---|---:|---|---|---|---|\n")
	for _, field := range fields {
		buf.WriteString("| `" + escapePipe(field.Path) + "` | `" + escapePipe(field.Type) + "` | ")
		if field.Required {
			buf.WriteString("yes")
		} else {
			buf.WriteString("no")
		}
		buf.WriteString(" | `" + escapePipe(field.Default) + "` | `" + escapePipe(field.Enum) + "` | " + escapePipe(field.Description) + " | `" + escapePipe(field.Example) + "` |\n")
	}
	return buf.String()
}

func filterFields(fields []Field, keep func(Field) bool) []Field {
	var out []Field
	for _, field := range fields {
		if keep(field) {
			out = append(out, field)
		}
	}
	return out
}

func dedupeFields(fields []Field) []Field {
	seen := map[string]bool{}
	var out []Field
	for _, field := range fields {
		if seen[field.Path] {
			continue
		}
		seen[field.Path] = true
		out = append(out, field)
	}
	return out
}

func requiredSet(raw any) map[string]bool {
	set := map[string]bool{}
	for _, item := range toStrings(raw) {
		set[item] = true
	}
	return set
}

func fieldType(root, node map[string]any) string {
	node = resolveSchemaNode(root, node)
	if t, _ := node["type"].(string); t != "" {
		if t == "array" {
			items, _ := node["items"].(map[string]any)
			items = resolveSchemaNode(root, items)
			if itemType, _ := items["type"].(string); itemType != "" {
				return "array<" + itemType + ">"
			}
			if len(items) > 0 {
				return "array<object>"
			}
		}
		return t
	}
	if node["const"] != nil {
		return "string"
	}
	if node["properties"] != nil {
		return "object"
	}
	return "unknown"
}

func inferExample(root, node map[string]any) string {
	node = resolveSchemaNode(root, node)
	if value := node["const"]; value != nil {
		return valueString(value)
	}
	if value := node["default"]; value != nil {
		return valueString(value)
	}
	if values := toStrings(node["enum"]); len(values) > 0 {
		return values[0]
	}
	switch fieldType(root, node) {
	case "string":
		return "example"
	case "integer", "number":
		return "1"
	case "boolean":
		return "true"
	case "array<string>":
		return "[example]"
	case "array<object>":
		return "[{...}]"
	case "object":
		return "{...}"
	default:
		return ""
	}
}

func renderNestedSections(fields []Field, prefix string) string {
	sections := nestedSectionPaths(fields, prefix)
	if len(sections) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for _, section := range sections {
		sectionFields := directChildFields(fields, section)
		if len(sectionFields) == 0 {
			continue
		}
		buf.WriteString("### `" + section + "`\n\n")
		buf.WriteString(renderFieldTable(sectionFields))
		buf.WriteString("\n")
	}
	return buf.String()
}

func directChildFields(fields []Field, prefix string) []Field {
	return filterFields(fields, func(f Field) bool {
		if prefix == "" {
			return !strings.Contains(f.Path, ".") && !strings.Contains(f.Path, "[]")
		}
		if !strings.HasPrefix(f.Path, prefix+".") && !strings.HasPrefix(f.Path, prefix+"[]") {
			return false
		}
		remainder := strings.TrimPrefix(strings.TrimPrefix(f.Path, prefix+"."), prefix+"[]")
		return !strings.Contains(remainder, ".") && !strings.Contains(remainder, "[]")
	})
}

func nestedSectionPaths(fields []Field, prefix string) []string {
	seen := map[string]bool{}
	var out []string
	for _, field := range fields {
		if field.Type != "object" && field.Type != "array<object>" {
			continue
		}
		if field.Path == "" || !strings.Contains(field.Path, ".") {
			if prefix == "" || field.Path == prefix {
				continue
			}
		}
		if prefix != "" && !strings.HasPrefix(field.Path, prefix+".") {
			continue
		}
		if seen[field.Path] {
			continue
		}
		seen[field.Path] = true
		out = append(out, field.Path)
	}
	sort.Strings(out)
	return out
}

func resolveSchemaNode(root, node map[string]any) map[string]any {
	if node == nil {
		return nil
	}
	ref, _ := node["$ref"].(string)
	if ref == "" || !strings.HasPrefix(ref, "#/") {
		return node
	}
	parts := strings.Split(strings.TrimPrefix(ref, "#/"), "/")
	var current any = root
	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return node
		}
		current = m[part]
	}
	resolved, ok := current.(map[string]any)
	if !ok {
		return node
	}
	return resolved
}

func enumString(raw any) string { return strings.Join(toStrings(raw), ", ") }

func valueString(v any) string {
	if v == nil {
		return ""
	}
	return strings.TrimSpace(fmt.Sprint(v))
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func toStrings(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func mapValue(root any, path ...string) any {
	current, _ := root.(map[string]any)
	for _, key := range path {
		if current == nil {
			return nil
		}
		next := current[key]
		if m, ok := next.(map[string]any); ok {
			current = m
			continue
		}
		if key == path[len(path)-1] {
			return next
		}
		return nil
	}
	return current
}

func joinPath(prefix, key string) string {
	if prefix == "" {
		return key
	}
	return prefix + "." + key
}

func prefixDotJoin(prefix string, items []string) string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, prefixPath(prefix, item))
	}
	return strings.Join(out, ", ")
}

func prefixPath(prefix, item string) string {
	if prefix == "" {
		return fmt.Sprintf("`%s`", item)
	}
	return fmt.Sprintf("`%s.%s`", prefix, item)
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func familyTitleFallback(family string) string {
	if family == "" {
		return ""
	}
	return strings.ToUpper(family[:1]) + family[1:]
}

func dedupeStrings(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, item := range items {
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		out = append(out, item)
	}
	return out
}

func toAnySliceFromUnknown(v any) []any { items, _ := v.([]any); return items }

func escapePipe(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
