package schemadoc

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type PageInput struct {
	Kind        string
	PageSlug    string
	Title       string
	Description string
	Visibility  string
	SchemaPath  string
	Schema      map[string]any
	Meta        ToolMetadata
	Actions     []string
	Required    []string
	Spec        map[string]any
}

type Field struct {
	Path        string
	Type        string
	Required    bool
	Default     string
	Enum        string
	Description string
	Example     string
}

type ActionDetail struct {
	Action   string
	Fields   []Field
	Rules    []string
	Example  string
	Required []string
}

type PageOverrides struct {
	FieldDocs      map[string]FieldDoc
	MinimalExample string
	Notes          []string
}

func RenderToolPage(in PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + in.Kind + "\n\n")
	buf.WriteString(in.firstNonEmpty(in.Meta.Summary, in.Description) + "\n\n")
	buf.WriteString("## Summary\n\n")
	buf.WriteString("- kind: `" + in.Kind + "`\n")
	buf.WriteString("- visibility: `" + in.Visibility + "`\n")
	buf.WriteString("- schema: `../../../" + in.SchemaPath + "`\n")
	buf.WriteString("- category: `" + in.firstNonEmpty(in.Meta.Category, "other") + "`\n")
	if len(in.Actions) > 0 {
		buf.WriteString("- actions: `" + strings.Join(in.Actions, "`, `") + "`\n")
	}
	if strings.TrimSpace(in.Meta.WhenToUse) != "" {
		buf.WriteString("\n## When To Use\n\n" + in.Meta.WhenToUse + "\n")
	}
	buf.WriteString("\n## Minimal Example\n\n```yaml\n")
	buf.WriteString(minimalToolExample(in))
	buf.WriteString("```\n")
	if strings.TrimSpace(in.Meta.CuratedExample) != "" {
		buf.WriteString("\n## Realistic Example\n\n```yaml\n")
		buf.WriteString(in.Meta.CuratedExample)
		buf.WriteString("```\n")
	}
	fields := CollectFields(in.Schema)
	applyFieldDocs(fields, in.Meta.FieldDocs)
	buf.WriteString("\n## Fields\n\n")
	buf.WriteString(renderFieldTable(filterFields(fields, func(f Field) bool { return !strings.HasPrefix(f.Path, "spec.") })))
	buf.WriteString("\n## Spec Fields\n\n")
	buf.WriteString(renderFieldTable(filterFields(fields, func(f Field) bool { return strings.HasPrefix(f.Path, "spec.") })))
	if nested := renderNestedSections(fields, "spec"); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	rules := ExtractRules(in.Spec, "spec")
	if len(rules) > 0 {
		buf.WriteString("\n## Validation Rules\n\n")
		for _, rule := range rules {
			buf.WriteString("- " + rule + "\n")
		}
	}
	if len(in.Meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range in.Meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	if len(in.Actions) > 0 {
		buf.WriteString("\n## Actions\n\n")
		for _, action := range in.Actions {
			detail := buildActionDetail(in, fields, rules, action)
			buf.WriteString("### `" + action + "`\n\n")
			note := in.Meta.ActionNotes[action]
			if strings.TrimSpace(note) == "" {
				note = "Refer to the schema constraints below for this action-specific branch."
			}
			buf.WriteString(note + "\n")
			if len(detail.Required) > 0 {
				buf.WriteString("\n- required fields: " + strings.Join(wrapPaths(detail.Required), ", ") + "\n")
			}
			if len(detail.Fields) > 0 {
				buf.WriteString("\n#### Fields\n\n")
				buf.WriteString(renderFieldTable(detail.Fields))
			}
			if len(detail.Rules) > 0 {
				buf.WriteString("\n#### Rules\n\n")
				for _, rule := range detail.Rules {
					buf.WriteString("- " + rule + "\n")
				}
			}
			if strings.TrimSpace(detail.Example) != "" {
				buf.WriteString("\n#### Example\n\n```yaml\n")
				buf.WriteString(detail.Example)
				buf.WriteString("```\n")
			}
		}
	}
	buf.WriteString("\n## Related\n\n")
	buf.WriteString("- `../index.md`\n")
	buf.WriteString("- `../examples/" + in.PageSlug + ".md`\n")
	return buf.Bytes()
}

func RenderToolExamplePage(in PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + in.Kind + " Examples\n\n")
	buf.WriteString("## Minimal Example\n\n```yaml\n")
	buf.WriteString(minimalToolExample(in))
	buf.WriteString("```\n")
	if strings.TrimSpace(in.Meta.CuratedExample) != "" {
		buf.WriteString("\n## Curated Example\n\n```yaml\n")
		buf.WriteString(in.Meta.CuratedExample)
		buf.WriteString("```\n")
	}
	buf.WriteString("\n## Related\n\n- `../tools/" + in.PageSlug + ".md`\n")
	return buf.Bytes()
}

func RenderToolsIndex(inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Tool Schemas\n\n")
	buf.WriteString("Generated reference pages for each typed workflow step.\n\n")
	for _, in := range inputs {
		buf.WriteString("## `" + in.Kind + "`\n\n")
		buf.WriteString("- page: `" + in.PageSlug + ".md`\n")
		buf.WriteString("- category: `" + in.firstNonEmpty(in.Meta.Category, "other") + "`\n")
		buf.WriteString("- summary: " + in.firstNonEmpty(in.Meta.Summary, in.Description) + "\n")
	}
	return buf.Bytes()
}

func RenderExamplesIndex(inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Schema Examples\n\n")
	buf.WriteString("Every schema gets a minimal generated example. High-value kinds also include curated examples.\n\n")
	for _, in := range inputs {
		kind := in.Kind
		buf.WriteString("- `" + kind + "`: `" + in.PageSlug + ".md`\n")
	}
	return buf.Bytes()
}

func RenderSchemaIndex(workflowPath, toolDefPath string, inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Schema Reference\n\n")
	buf.WriteString("This is the generated entrypoint for deck schema documentation.\n\n")
	buf.WriteString("## Start Here\n\n")
	buf.WriteString("- workflow schema: `workflow.md`\n")
	buf.WriteString("- tool definition schema: `tool-definition.md`\n")
	buf.WriteString("- tool schema pages: `tools/index.md`\n")
	buf.WriteString("- examples: `examples/index.md`\n\n")
	buf.WriteString("## Raw JSON Schemas\n\n")
	buf.WriteString("- `../../../" + workflowPath + "`\n")
	buf.WriteString("- `../../../" + toolDefPath + "`\n")
	buf.WriteString("- `../../../schemas/tools/*.schema.json`\n\n")
	buf.WriteString("## Available Tool Pages\n\n")
	for _, in := range inputs {
		buf.WriteString("- `tools/" + in.PageSlug + ".md`: `" + in.Kind + "`\n")
	}
	return buf.Bytes()
}

func RenderWorkflowPage(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + firstNonEmpty(meta.Title, "Workflow Schema") + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Top-level workflow authoring reference for deck workflows.") + "\n\n")
	buf.WriteString("- schema: `../../../" + schemaPath + "`\n\n")
	buf.WriteString("## Minimal Example\n\n```yaml\n" + firstNonEmpty(meta.MinimalExample, "role: apply\nversion: v1alpha1\nsteps:\n  - id: example-step\n    kind: File\n    spec:\n      action: install\n      path: /tmp/example\n      content: hello\n") + "```\n")
	buf.WriteString("\n## Realistic Example\n\n```yaml\n" + firstNonEmpty(meta.RealisticExample, "role: prepare\nversion: v1alpha1\nartifacts:\n  files:\n    - group: runtime-binaries\n      items:\n        - id: runc\n          source:\n            url: https://mirror.example.invalid/runc\n          output:\n            path: bin/runc\n") + "```\n")
	fields := CollectFields(schema)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("\n## Fields\n\n")
	buf.WriteString(renderFieldTable(fields))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	buf.WriteString("\n## Validation Rules\n\n")
	for _, rule := range ExtractRules(schema, "") {
		buf.WriteString("- " + rule + "\n")
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func RenderToolDefinitionPage(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + firstNonEmpty(meta.Title, "Tool Definition Schema") + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Reference for tool definition manifests.") + "\n\n")
	buf.WriteString("- schema: `../../../" + schemaPath + "`\n\n")
	buf.WriteString("## Minimal Example\n\n```yaml\n" + firstNonEmpty(meta.MinimalExample, "apiVersion: deck/v1\nkind: ToolDefinition\nmetadata:\n  name: Example\nspec:\n  version: v1\n  summary: Example tool\n  category: shared\n  inputSchema: {}\n") + "```\n")
	buf.WriteString("\n## Realistic Example\n\n```yaml\n" + firstNonEmpty(meta.RealisticExample, "apiVersion: deck/v1\nkind: ToolDefinition\nmetadata:\n  name: Example\nspec:\n  version: v1\n  summary: Example tool\n  category: shared\n  inputSchema: {}\n") + "```\n")
	fields := CollectFields(schema)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("## Fields\n\n")
	buf.WriteString(renderFieldTable(fields))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	buf.WriteString("\n## Validation Rules\n\n")
	for _, rule := range ExtractRules(schema, "") {
		buf.WriteString("- " + rule + "\n")
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func CollectFields(schema map[string]any) []Field {
	var fields []Field
	collectFields(schema, schema, "", &fields)
	return dedupeFields(fields)
}

func collectFields(root, node map[string]any, prefix string, fields *[]Field) {
	node = resolveSchemaNode(root, node)
	props, _ := node["properties"].(map[string]any)
	if len(props) == 0 {
		return
	}
	req := requiredSet(node["required"])
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		child = resolveSchemaNode(root, child)
		path := joinPath(prefix, key)
		field := Field{
			Path:        path,
			Type:        fieldType(root, child),
			Required:    req[key],
			Default:     valueString(child["default"]),
			Enum:        enumString(child["enum"]),
			Description: stringValue(child["description"]),
			Example:     inferExample(root, child),
		}
		*fields = append(*fields, field)
		if field.Type == "object" {
			collectFields(root, child, path, fields)
		}
		items, _ := resolveSchemaNode(root, child)["items"].(map[string]any)
		items = resolveSchemaNode(root, items)
		if field.Type == "array<object>" && len(items) > 0 {
			collectFields(root, items, path+"[]", fields)
		}
	}
}

func ExtractRules(node map[string]any, prefix string) []string {
	var rules []string
	if anyOf, ok := node["anyOf"].([]any); ok {
		var requiredGroups []string
		for _, raw := range anyOf {
			entry, _ := raw.(map[string]any)
			req := toStrings(entry["required"])
			if len(req) > 0 {
				requiredGroups = append(requiredGroups, strings.Join(req, ", "))
			}
		}
		if len(requiredGroups) > 0 && prefix == "" {
			rules = append(rules, "At least one of the top-level groups `artifacts`, `imports`, `phases`, or `steps` must be present.")
		}
		for _, raw := range anyOf {
			entry, _ := raw.(map[string]any)
			if strings.Contains(fmt.Sprint(entry), "const") {
				rules = append(rules, "At least one of the listed branches must match.")
				break
			}
		}
	}
	if oneOf, ok := node["oneOf"].([]any); ok && len(oneOf) > 0 {
		for _, raw := range oneOf {
			entry, _ := raw.(map[string]any)
			req := toStrings(entry["required"])
			notReq := toStrings(mapValue(entry, "not", "required"))
			if len(req) == 1 && len(notReq) == 1 {
				rules = append(rules, fmt.Sprintf("Exactly one of %s or %s must be set.", prefixPath(prefix, req[0]), prefixPath(prefix, notReq[0])))
				break
			}
		}
	}
	if allOf, ok := node["allOf"].([]any); ok {
		for _, raw := range allOf {
			entry, _ := raw.(map[string]any)
			ifNode, _ := entry["if"].(map[string]any)
			thenNode, _ := entry["then"].(map[string]any)
			action := stringValue(mapValue(ifNode, "properties", "action", "const"))
			if action == "" {
				enumAction := toStrings(mapValue(ifNode, "properties", "action", "enum"))
				if len(enumAction) > 0 {
					required := toStrings(thenNode["required"])
					if len(required) > 0 {
						rules = append(rules, fmt.Sprintf("When `%s.action` is one of `%s`, %s are required.", prefix, strings.Join(enumAction, "`, `"), prefixDotJoin(prefix, required)))
					}
				}
				continue
			}
			required := toStrings(thenNode["required"])
			if len(required) > 0 {
				rules = append(rules, fmt.Sprintf("When `%s.action=%s`, %s are required.", prefix, action, prefixDotJoin(prefix, required)))
			}
			if anyOf, ok := thenNode["anyOf"].([]any); ok && len(anyOf) > 0 {
				var choices []string
				for _, choiceRaw := range anyOf {
					choice, _ := choiceRaw.(map[string]any)
					choiceReq := toStrings(choice["required"])
					for _, item := range choiceReq {
						choices = append(choices, fmt.Sprintf("`%s.%s`", prefix, item))
					}
				}
				if len(choices) > 0 {
					rules = append(rules, fmt.Sprintf("When `%s.action=%s`, at least one of %s must be set.", prefix, action, strings.Join(choices, " or ")))
				}
			}
		}
	}
	if notNode, ok := node["not"].(map[string]any); ok {
		if allOf, ok := notNode["allOf"].([]any); ok && len(allOf) > 0 && prefix == "" {
			rules = append(rules, "Top-level `phases` and top-level `steps` cannot both be set in the same workflow.")
		}
	}
	return dedupeStrings(rules)
}

func minimalToolExample(in PageInput) string {
	if strings.TrimSpace(in.Meta.MinimalExample) != "" {
		return in.Meta.MinimalExample
	}
	obj := map[string]any{
		"id":         "example-" + strings.ToLower(in.Kind),
		"apiVersion": "deck/v1alpha1",
		"kind":       in.Kind,
		"spec":       minimalObject(in.Spec),
	}
	raw, _ := yaml.Marshal(obj)
	return string(raw)
}

func applyFieldDocs(fields []Field, overrides map[string]FieldDoc) {
	for i := range fields {
		override, ok := overrides[fields[i].Path]
		if !ok {
			continue
		}
		if strings.TrimSpace(override.Description) != "" {
			fields[i].Description = override.Description
		}
		if strings.TrimSpace(override.Example) != "" {
			fields[i].Example = override.Example
		}
	}
}

func buildActionDetail(in PageInput, fields []Field, rules []string, action string) ActionDetail {
	required := actionRequiredFields(in.Spec, action)
	var actionFields []Field
	requiredSet := map[string]bool{}
	for _, item := range required {
		requiredSet[item] = true
	}
	for _, field := range fields {
		if field.Path == "spec.action" || requiredSet[field.Path] {
			actionFields = append(actionFields, field)
			continue
		}
		for _, item := range required {
			if strings.HasPrefix(field.Path, item+".") || strings.HasPrefix(field.Path, item+"[]") {
				actionFields = append(actionFields, field)
				break
			}
		}
	}
	var actionRules []string
	needle := "`spec.action=" + action + "`"
	needleMulti := "`spec.action` is one of `" + action + "`"
	for _, rule := range rules {
		if strings.Contains(rule, needle) || strings.Contains(rule, needleMulti) || strings.Contains(rule, "`spec.action` is one of `"+action+"`") {
			actionRules = append(actionRules, rule)
		}
	}
	return ActionDetail{
		Action:   action,
		Fields:   dedupeFields(actionFields),
		Rules:    dedupeStrings(actionRules),
		Example:  in.Meta.ActionExamples[action],
		Required: required,
	}
}

func actionRequiredFields(spec map[string]any, action string) []string {
	var required []string
	for _, raw := range toAnySliceFromUnknown(spec["allOf"]) {
		entry, _ := raw.(map[string]any)
		ifNode, _ := entry["if"].(map[string]any)
		thenNode, _ := entry["then"].(map[string]any)
		constAction := stringValue(mapValue(ifNode, "properties", "action", "const"))
		if constAction == action {
			for _, item := range toStrings(thenNode["required"]) {
				required = append(required, prefixSpec(item))
			}
			for _, anyRaw := range toAnySliceFromUnknown(thenNode["anyOf"]) {
				choice, _ := anyRaw.(map[string]any)
				for _, item := range toStrings(choice["required"]) {
					required = append(required, prefixSpec(item))
				}
			}
		}
		enumActions := toStrings(mapValue(ifNode, "properties", "action", "enum"))
		for _, enumAction := range enumActions {
			if enumAction == action {
				for _, item := range toStrings(thenNode["required"]) {
					required = append(required, prefixSpec(item))
				}
			}
		}
	}
	return dedupeStrings(required)
}

func minimalObject(node map[string]any) map[string]any {
	obj := map[string]any{}
	req := requiredSet(node["required"])
	props, _ := node["properties"].(map[string]any)
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child, _ := props[key].(map[string]any)
		if !req[key] && key != "action" {
			continue
		}
		obj[key] = minimalValue(node, child)
	}
	if allOf, ok := node["allOf"].([]any); ok {
		for _, raw := range allOf {
			entry, _ := raw.(map[string]any)
			action := stringValue(mapValue(entry, "if", "properties", "action", "const"))
			if action != "" {
				obj["action"] = action
				for _, field := range toStrings(mapValue(entry, "then", "required")) {
					if child, ok := props[field].(map[string]any); ok {
						obj[field] = minimalValue(node, child)
					}
				}
				for _, anyRaw := range toAnySliceFromUnknown(mapValue(entry, "then", "anyOf")) {
					choice, _ := anyRaw.(map[string]any)
					for _, field := range toStrings(choice["required"]) {
						if child, ok := props[field].(map[string]any); ok {
							obj[field] = minimalValue(node, child)
							break
						}
					}
					break
				}
				break
			}
		}
	}
	applyBranchRequirements(obj, node, props)
	return obj
}

func applyBranchRequirements(obj map[string]any, node map[string]any, props map[string]any) {
	for _, groupKey := range []string{"anyOf", "oneOf"} {
		for _, raw := range toAnySliceFromUnknown(node[groupKey]) {
			branch, _ := raw.(map[string]any)
			for _, field := range toStrings(branch["required"]) {
				if _, exists := obj[field]; exists {
					continue
				}
				if child, ok := props[field].(map[string]any); ok {
					obj[field] = minimalValue(node, child)
					return
				}
			}
		}
	}
}

func minimalValue(root, node map[string]any) any {
	node = resolveSchemaNode(root, node)
	if value := node["const"]; value != nil {
		return value
	}
	if values := toStrings(node["enum"]); len(values) > 0 {
		return values[0]
	}
	switch fieldType(root, node) {
	case "string":
		return "example"
	case "integer":
		return 1
	case "number":
		return 1
	case "boolean":
		return true
	case "array<string>":
		return []string{"example"}
	case "array<object>":
		items, _ := node["items"].(map[string]any)
		return []any{minimalObject(resolveSchemaNode(root, items))}
	case "array":
		return []any{"example"}
	case "object":
		return minimalObject(node)
	default:
		return "example"
	}
}

func renderFieldTable(fields []Field) string {
	if len(fields) == 0 {
		return "No documented fields.\n"
	}
	var buf bytes.Buffer
	buf.WriteString("| Key | Type | Required | Default | Enum | Description | Example |\n")
	buf.WriteString("|---|---|---:|---|---|---|---|\n")
	for _, field := range fields {
		buf.WriteString("| `" + escapePipe(field.Path) + "` | `" + escapePipe(field.Type) + "` | ")
		if field.Required {
			buf.WriteString("yes")
		} else {
			buf.WriteString("no")
		}
		buf.WriteString(" | `" + escapePipe(field.Default) + "` | `" + escapePipe(field.Enum) + "` | " + escapePipe(field.Description) + " | `" + escapePipe(field.Example) + "` |\n")
	}
	return buf.String()
}

func filterFields(fields []Field, keep func(Field) bool) []Field {
	var out []Field
	for _, field := range fields {
		if keep(field) {
			out = append(out, field)
		}
	}
	return out
}

func dedupeFields(fields []Field) []Field {
	seen := map[string]bool{}
	var out []Field
	for _, field := range fields {
		if seen[field.Path] {
			continue
		}
		seen[field.Path] = true
		out = append(out, field)
	}
	return out
}

func requiredSet(raw any) map[string]bool {
	set := map[string]bool{}
	for _, item := range toStrings(raw) {
		set[item] = true
	}
	return set
}

func fieldType(root, node map[string]any) string {
	node = resolveSchemaNode(root, node)
	if t, _ := node["type"].(string); t != "" {
		if t == "array" {
			items, _ := node["items"].(map[string]any)
			items = resolveSchemaNode(root, items)
			if itemType, _ := items["type"].(string); itemType != "" {
				return "array<" + itemType + ">"
			}
			if len(items) > 0 {
				return "array<object>"
			}
		}
		return t
	}
	if node["const"] != nil {
		return "string"
	}
	if node["properties"] != nil {
		return "object"
	}
	return "unknown"
}

func inferExample(root, node map[string]any) string {
	node = resolveSchemaNode(root, node)
	if value := node["const"]; value != nil {
		return valueString(value)
	}
	if value := node["default"]; value != nil {
		return valueString(value)
	}
	if values := toStrings(node["enum"]); len(values) > 0 {
		return values[0]
	}
	switch fieldType(root, node) {
	case "string":
		return "example"
	case "integer", "number":
		return "1"
	case "boolean":
		return "true"
	case "array<string>":
		return "[example]"
	case "array<object>":
		return "[{...}]"
	case "object":
		return "{...}"
	default:
		return ""
	}
}

func renderNestedSections(fields []Field, prefix string) string {
	sections := nestedSectionPaths(fields, prefix)
	if len(sections) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for _, section := range sections {
		sectionFields := filterFields(fields, func(f Field) bool {
			return strings.HasPrefix(f.Path, section+".") || strings.HasPrefix(f.Path, section+"[]")
		})
		if len(sectionFields) == 0 {
			continue
		}
		buf.WriteString("### `" + section + "`\n\n")
		buf.WriteString(renderFieldTable(sectionFields))
		buf.WriteString("\n")
	}
	return buf.String()
}

func nestedSectionPaths(fields []Field, prefix string) []string {
	seen := map[string]bool{}
	var out []string
	for _, field := range fields {
		if field.Type != "object" && field.Type != "array<object>" {
			continue
		}
		if field.Path == "" || !strings.Contains(field.Path, ".") {
			if prefix == "" || field.Path == prefix {
				continue
			}
		}
		if prefix != "" && !strings.HasPrefix(field.Path, prefix+".") {
			continue
		}
		if seen[field.Path] {
			continue
		}
		seen[field.Path] = true
		out = append(out, field.Path)
	}
	sort.Strings(out)
	return out
}

func resolveSchemaNode(root, node map[string]any) map[string]any {
	if node == nil {
		return nil
	}
	ref, _ := node["$ref"].(string)
	if ref == "" || !strings.HasPrefix(ref, "#/") {
		return node
	}
	parts := strings.Split(strings.TrimPrefix(ref, "#/"), "/")
	var current any = root
	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return node
		}
		current = m[part]
	}
	resolved, ok := current.(map[string]any)
	if !ok {
		return node
	}
	return resolved
}

func enumString(raw any) string { return strings.Join(toStrings(raw), ", ") }

func valueString(v any) string {
	if v == nil {
		return ""
	}
	return strings.TrimSpace(fmt.Sprint(v))
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func toStrings(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func mapValue(root any, path ...string) any {
	current, _ := root.(map[string]any)
	for _, key := range path {
		if current == nil {
			return nil
		}
		next := current[key]
		if m, ok := next.(map[string]any); ok {
			current = m
			continue
		}
		if key == path[len(path)-1] {
			return next
		}
		return nil
	}
	return current
}

func joinPath(prefix, key string) string {
	if prefix == "" {
		return key
	}
	return prefix + "." + key
}

func prefixDotJoin(prefix string, items []string) string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, prefixPath(prefix, item))
	}
	return strings.Join(out, ", ")
}

func prefixSpec(item string) string {
	return "spec." + item
}

func wrapPaths(items []string) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, "`"+item+"`")
	}
	return out
}

func prefixPath(prefix, item string) string {
	if prefix == "" {
		return fmt.Sprintf("`%s`", item)
	}
	return fmt.Sprintf("`%s.%s`", prefix, item)
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func dedupeStrings(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, item := range items {
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		out = append(out, item)
	}
	return out
}

func toAnySliceFromUnknown(v any) []any { items, _ := v.([]any); return items }

func escapePipe(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

func (in PageInput) firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}
